config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "grids#new"

  resources :grids, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/grid.rb
class Grid < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController

  def new
    @grid = Grid.new
  end

  def create
    formatted_grid = grid_params[:input].split("\n").map{ |i| i.split('') }
    result = ConductivePathService.new(formatted_grid).find
    @grid = Grid.create(input: grid_params[:input], result: result.merge(formatted_grid: formatted_grid))

    redirect_to action: :index
  end

  def index
    @grids = Grid.order(id: :desc).page(params[:page]).per(5)
  end

  def grid_params
    params.require(:grid).permit(:input)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/views/grids/index.html.erb
<style>
  .conductive-path {
    background-color: yellow;
  }
</style>

<div class="container">
  <div class="text-end"><%= link_to "Create grid", new_grid_path, class: "btn btn-primary mt-2" %></div>

  <h2>History</h2>

  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Executed At</th>
        <th>Evaluation Result</th>
        <th>Input</th>
      </tr>
    </thead>
    <tbody>
      <% @grids.each do |grid| %>
        <tr>
          <td><%= grid.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
          <td><%= grid.result['evaluation'] ? "YES (#{grid.result['conductive_paths'].size})" : 'NO' %></td>
          <td>
            <div class="grid-input">
              <% formatted_grid = grid.result['formatted_grid'] %>
              <% if formatted_grid.present? %>
                <% grid.result['formatted_grid'].each_with_index do |row, row_index| %>
                  <div class="grid-row">
                    <% row.each_with_index do |element, col_index| %>
                      <% if grid.result['conductive_paths'].present? && grid.result['conductive_path_mappings']["#{row_index}-#{col_index}"] %>
                        <span class="conductive-path"><%= element %></span>
                      <% else %>
                        <%= element %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @grids %>
</div>

app/views/grids/new.html.erb
<div class="container">
  <div class="text-end"><%= link_to "Back to history", grids_path, class: "btn btn-primary mt-2" %></div>

  <%= form_for @grid do |f| %>
    <div class="form-group">
      <%= f.label :input, "Grid Input" %>
      <%= f.text_area :input, class: "form-control" %>
    </div>

    <%= f.submit "Create Grid", class: "btn btn-primary mt-2" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConductivePathFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>